[package]
name = "onvif-media-transcoder"
version = "0.31.0"
edition = "2024"
rust-version = "1.87"
description = "Exposes an HLS/RTSP stream as an ONVIF Profile S camera with WS-Discovery"
license = "MIT"
repository = "https://github.com/W4ff1e/onvif-media-transcoder"
publish = false

[dependencies]
base64 = "0.23.1"
chrono = "0.4.42"
clap = { version = "4.5.52", features = ["derive", "env"] }
md5 = "0.8"
percent-encoding = "2.3"
roxmltree = "0.21.1"
sha1 = "0.10.6"
signal-hook = "0.3.18"
socket2 = "0.6"
tiny_http = "0.12.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.18.1", features = ["v4", "v5"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
