// ONVIF Endpoints Module
// Contains lists of supported and unsupported ONVIF endpoints

pub const UNSUPPORTED_ENDPOINTS: &[&str] = &[
    // Device Management Service
    "GetSystemDateAndTime",
    "SetSystemDateAndTime",
    "GetSystemLog",
    "GetSystemSupportInformation",
    "GetUsers",
    "CreateUsers",
    "DeleteUsers",
    "SetUser",
    "GetWsdlUrl",
    "GetPasswordComplexityOptions",
    "GetPasswordComplexityConfiguration",
    "SetPasswordComplexityConfiguration",
    "GetPasswordHistoryConfiguration",
    "SetPasswordHistoryConfiguration",
    "GetAuthFailureWarningOptions",
    "GetAuthFailureWarningConfiguration",
    "SetAuthFailureWarningConfiguration",
    "GetSystemUris",
    "StartFirmwareUpgrade",
    "StartSystemRestore",
    "GetSystemBackup",
    "GetSystemLog",
    "GetSupportInformation",
    "GetStorageConfigurations",
    "CreateStorageConfiguration",
    "GetStorageConfiguration",
    "SetStorageConfiguration",
    "DeleteStorageConfiguration",
    // Media Service - Configuration Management
    "CreateProfile",
    "GetProfile",
    "DeleteProfile",
    "GetVideoSourceConfiguration",
    "GetVideoEncoderConfiguration",
    "GetAudioSourceConfiguration",
    "GetAudioEncoderConfiguration",
    "SetVideoSourceConfiguration",
    "SetVideoEncoderConfiguration",
    "SetAudioSourceConfiguration",
    "SetAudioEncoderConfiguration",
    "GetCompatibleVideoEncoderConfigurations",
    "GetCompatibleVideoSourceConfigurations",
    "GetCompatibleAudioEncoderConfigurations",
    "GetCompatibleAudioSourceConfigurations",
    "GetVideoEncoderConfigurationOptions",
    "GetAudioEncoderConfigurationOptions",
    "GetVideoSourceConfigurationOptions",
    "GetAudioSourceConfigurationOptions",
    "GetGuaranteedNumberOfVideoEncoderInstances",
    "GetGuaranteedNumberOfAudioEncoderInstances",
    // Media Service - Streaming
    "StartMulticastStreaming",
    "StopMulticastStreaming",
    // PTZ Service
    "GetNodes",
    "GetNode",
    "GetConfiguration",
    "GetConfigurations",
    "SetConfiguration",
    "GetConfigurationOptions",
    "AbsoluteMove",
    "RelativeMove",
    "ContinuousMove",
    "Stop",
    "GetStatus",
    "SetHomePosition",
    "GotoHomePosition",
    "SetPreset",
    "GetPresets",
    "GotoPreset",
    "RemovePreset",
    // Analytics Service
    "GetSupportedAnalyticsModules",
    "GetAnalyticsModules",
    "CreateAnalyticsModules",
    "DeleteAnalyticsModules",
    "GetAnalyticsModule",
    "ModifyAnalyticsModules",
    // Events Service
    "Subscribe",
    "Unsubscribe",
    "CreatePullPoint",
    "GetEventProperties",
    "Renew",
    "GetMessages",
    "DestroyPullPoint",
    "Notify",
    "GetCurrentMessage",
    "SetSynchronizationPoint",
    // Imaging Service
    "GetServiceCapabilities",
    "GetImagingSettings",
    "SetImagingSettings",
    "GetOptions",
    "Move",
    "GetMoveOptions",
    "Stop",
    "GetStatus",
    "GetPresets",
    "GetCurrentPreset",
    "SetCurrentPreset",
    // Recording Service
    "CreateRecording",
    "DeleteRecording",
    "GetRecordings",
    "SetRecordingConfiguration",
    "GetRecordingConfiguration",
    "GetRecordingOptions",
    "CreateTrack",
    "DeleteTrack",
    "GetTracks",
    "CreateRecordingJob",
    "DeleteRecordingJob",
    "GetRecordingJobs",
    "SetRecordingJobConfiguration",
    "GetRecordingJobConfiguration",
    "SetRecordingJobMode",
    "GetRecordingJobState",
    // Replay Service
    "GetServiceCapabilities",
    "GetReplayUri",
    "GetReplayConfiguration",
    "SetReplayConfiguration",
    // Search Service
    "GetServiceCapabilities",
    "GetMetadataSearchResults",
    "FindRecordings",
    "GetRecordingSummary",
    "GetRecordingInformation",
    "FindEvents",
    "GetEventSearchResults",
    "FindPTZPosition",
    "GetPTZPositionSearchResults",
    "GetSearchState",
    "EndSearch",
    // Receiver Service
    "GetServiceCapabilities",
    "GetReceivers",
    "GetReceiver",
    "CreateReceiver",
    "DeleteReceiver",
    "ConfigureReceiver",
    "SetReceiverMode",
    "GetReceiverState",
    // Display Service
    "GetServiceCapabilities",
    "GetLayout",
    "SetLayout",
    "GetDisplayOptions",
    "GetPaneConfigurations",
    "GetPaneConfiguration",
    "SetPaneConfigurations",
    "SetPaneConfiguration",
    "CreatePaneConfiguration",
    "DeletePaneConfiguration",
];
